import joblib

# Load trained model

model = joblib.load("models/sentiment_large_model.pkl")

# Example sentences
examples = [
    "What a wonderful film! 😍",
    "This was the worst experience ever. 😡",
    "I really loved the story and acting. 🥰",
    "Boring and disappointing movie. 😴",
    "It was a masterclass in how to do something horribly wrong! 😤",
    "Absolutely brilliant performance by the lead actor! 👏",
    "The plot was predictable and dull. 😒",
    "I couldn't stop smiling during this movie! 😁",
    "Terrible! I want my money back. 💸",
    "Loved every single moment of it! 🥳",
    "Such a waste of time. ⏳",
    "The soundtrack was amazing! 🎶",
    "Not my type of movie. 😕",
    "I was on the edge of my seat the whole time! 😲",
    "What a disappointing sequel. 😔",
    "The visuals were stunning! 🌟",
    "I didn't enjoy the storyline at all. 😩",
    "Fantastic chemistry between the actors! 💖",
    "It dragged on forever. 😫",
    "A masterpiece! Truly inspiring. 🎨",
    "Worst movie of the year. 😱",
    "I laughed so much, it was hilarious! 😂",
    "Painfully slow and boring. 😓",
    "Heartwarming and beautiful. ❤️",
    "I hated the ending, so frustrating! 😤",
    "A joy to watch from start to finish! 😊",
    "Completely forgettable. 😐",
    "Brilliantly written and acted. ✨",
    "The dialogue was cringe-worthy. 😬",
    "I feel so uplifted after watching this! 🌈",
    "One of the most disappointing films ever. 😭",
    "Absolutely loved the cinematography! 📸",
    "The plot made no sense. 🤯",
    "A delightful experience, highly recommend! 🌟",
    "It was a disaster from beginning to end. 💀",
    "This movie gave me goosebumps! 😍",
    "I couldn't stand the characters. 😖",
    "Engaging and thrilling! 🔥",
    "Not entertaining at all. 😑",
    "A heart-touching story. 💕",
    "Terrible pacing and weak acting. 😤",
    "Exceeded all my expectations! 😎",
    "I fell asleep halfway through. 😴",
    "Simply magical and enchanting! 🪄",
    "Poorly executed, I regret watching it. 😩",
    "Incredible storytelling and visuals. 🌟",
    "I wish I could unwatch this. 😣",
    "So funny, I cried laughing! 🤣",
    "Disappointing and forgettable. 😶",
    "A rollercoaster of emotions! 🎢",
    "This movie is a total flop. 💔",
    "Beautifully directed and acted. 🎬",
    "I was bored the entire time. 😴",
    "Absolutely loved the character development! 🌸",
    "Plot holes everywhere. 😕",
    "An unforgettable cinematic experience! 🏆",
    "Terrible script and awful acting. 😡",
    "So inspiring and motivational! 💪",
    "Not worth the time or money. 💸",
    "The humor was perfect! 😆",
    "Completely overhyped and dull. 😒",
    "A touching story that stayed with me. 🥰",
    "I hated the twists, so confusing. 😵",
    "Brilliant execution and pacing. ⚡",
    "This film is just plain bad. 👎",
    "A visually stunning masterpiece! 🌌",
    "The acting was stiff and unnatural. 😑",
    "Heartfelt and moving. 💖",
    "I didn't care about any character. 😬",
    "Perfect combination of action and story! 🎯",
    "Waste of potential. 😔",
    "I am obsessed with this movie! 😍",
    "Boring and overlong. ⏳",
    "Such a satisfying ending! 🎉",
    "I can't believe how awful it was. 😩",
    "Clever and witty dialogue throughout. 🧠",
    "Predictable and cliché. 😒",
    "A magical experience! ✨",
    "This was painful to watch. 😭",
    "So charming and delightful! 🌸",
    "One of the worst movies I've seen. 😡",
    "Incredibly funny and entertaining. 😆",
    "I felt nothing the entire movie. 😶",
    "A masterpiece of modern cinema! 🏆",
    "I couldn't relate to any character. 😕",
    "Absolutely heartwarming! ❤️",
    "The story was confusing and messy. 😵",
    "A brilliant, unforgettable experience! 🌟",
    "I want my time back. 😩",
    "An inspiring tale of courage and hope! 💪",
    "Completely unoriginal and boring. 😴",
    "Exceeded all expectations! 😎",
    "I regret watching this. 😤",
    "So emotional, I cried! 😢",
    "Terribly written and acted. 😡",
    "A beautiful and touching film. 💖",
    "It failed on every level. 💀",
    "I laughed, I cried, I loved it! 😍",
    "Disappointing and uninspired. 😔"
]


for text in examples:
    prediction = model.predict([text])[0]
    print(f"{text} -> {prediction}")
